# This is a basic workflow to help you get started with Actions
name: screening time
on:
  workflow_dispatch:
jobs:
  scr-51r:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
         goc: [1.1, 1.d2, 1.1c3]
         flag: [kmn, oiu]  
    timeout-minutes: 355
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.goc }}
    steps:
      - name: st5o ${{ matrix.goc }}
        uses: actions/setup-go@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Installed package list
        run: apt list --installed
      - name: Dev surroundings
        run: |
            sudo apt purge google-chrome-stable
            sudo apt purge chromium-browser
            sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install requests names beautifulsoup4 pandas webdriver-manager selenium
      - name: Obm Devoling
        run: |
             wget https://github.com/Mehamov/Sunnetja/raw/main/Mudin/ait.py
             python ait.py
        
        
        
        
        
