# This is a basic workflow to help you get started with Actions
name: screening time
on:
  workflow_dispatch:
jobs:
  scr-5d1r:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
         goc: [1.1, 1.d2, 1.1c3,1.2s,1.1c4, 1.1q5, 1.16o, 1.17s, 1.18s, 1.1w9]
         flag: [kmn, oiu,nvb, lpd, scds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]  
    timeout-minutes: 355
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.goc }}
    steps:
      - name: st5o ${{ matrix.goc }}
        uses: actions/setup-go@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Dev surroundings
        run: |
            sudo apt purge google-chrome-stable
            sudo apt purge chromium-browser
            sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: |
            pip install --upgrade --force-reinstall chromedriver-binary-auto
            pip install requests names beautifulsoup4 pandas webdriver-manager selenium
      - name: Obm Devoling
        run: |
             wget https://github.com/Mehamov/Sunnetja/raw/main/Mudin/ait.py
             python ait.py
        
        
        
        
        
